export const authActionTypes = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_REQUEST_SUCCESS: "LOGIN_REQUEST_SUCCESS",
    LOGIN_REQUEST_FAIL: "LOGIN_REQUEST_FAIL",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_REQUEST_SUCCESS: "LOGOUT_REQUEST_SUCCESS"
};

