export const countryActionTypes = {
    COUNTRY_LIST_REQUEST: "COUNTRY_LIST_REQUEST",
    COUNTRY_LIST_REQUEST_SUCCESS: "COUNTRY_LIST_REQUEST_SUCCESS",
    COUNTRY_LIST_REQUEST_FAILURE: "COUNTRY_LIST_REQUEST_FAILURE",

    COUNTRY_ADD_REQUEST: "COUNTRY_ADD_REQUEST",
    COUNTRY_ADD_REQUEST_SUCCESS: "COUNTRY_ADD_REQUEST_SUCCESS",
    COUNTRY_ADD_REQUEST_FAILURE: "COUNTRY_ADD_REQUEST_FAILURE",

    COUNTRY_EDIT_REQUEST: "COUNTRY_EDIT_REQUEST",
    COUNTRY_EDIT_REQUEST_SUCCESS: "COUNTRY_EDIT_REQUEST_SUCCESS",
    COUNTRY_EDIT_REQUEST_FAILURE: "COUNTRY_EDIT_REQUEST_FAILURE"
}