export const languageActionTypes = {
    LANGUGAE_LIST_REQUEST: "LANGUAGE_LIST_REQUEST",
    LANGUAGE_LIST_REQUEST_SUCCESS: "LANGUAGE_LIST_REQUEST_SUCCESS",
    LANGUAGE_LIST_REQUEST_FAILURE: "LANGUAGE_LIST_REQUEST_FAILURE",

    LANGUGAE_ADD_REQUEST: "LANGUGAE_ADD_REQUEST",
    LANGUGAE_ADD_REQUEST_SUCCESS: "LANGUGAE_ADD_REQUEST_SUCCESS",
    LANGUGAE_ADD_REQUEST_FAILURE: "LANGUGAE_ADD_REQUEST_FAILURE",

    LANGUGAE_EDIT_REQUEST: "LANGUGAE_EDIT_REQUEST",
    LANGUGAE_EDIT_REQUEST_SUCCESS: "LANGUGAE_EDIT_REQUEST_SUCCESS",
    LANGUGAE_EDIT_REQUEST_FAILURE: "LANGUGAE_EDIT_REQUEST_FAILURE"
}